name: Google-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Google Remote Desktop
      run: |
        $msiPath = "$($env:TEMP)\chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile $msiPath
        Start-Process msiexec.exe -Wait -ArgumentList "/i $msiPath /qn"
        
    - name: Setup and Run
      shell: powershell
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="ВСТАВЬ_НОВЫЙ_КОД_ТУТ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
        
    - name: Keep Alive
      run: |
        Write-Host "RDP запущен. Ваш PIN: 123456"
        Write-Host "Ожидание автоматической остановки системы..."
        while($true) { Start-Sleep -Seconds 60 }
