name: Google-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Google Remote Desktop
      run: |
        $msiPath = "$($env:TEMP)\chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile $msiPath
        Start-Process msiexec.exe -Wait -ArgumentList "/i $msiPath /qn"
        
    - name: Setup and Run
      shell: powershell
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0ASc3gC0utwdL7IMpCl0HAhY6a7NwVqJjm8ZKiDi825Ry1SK3EE8Lg20ZdhSyvApSszkStw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
        
    - name: Keep Alive
      run: |
        Write-Host "RDP запущен. Теперь переходи на remotedesktop.google.com/access"
        Start-Sleep -Seconds 21600
